### ISSUE TITLE
Ethminer: disable hunter via flag and not via sed

### ISSUE THREAD

**Issue by EoD** [reagentoo/gentoo-overlay#5]
Basically get rid of the sed commands: https://github.com/reagentoo/gentoo-overlay/blob/964201b61c966a88621d0d91e620a46c51dec62a/net-p2p/ethminer/ethminer-9999.ebuild#L49-L74

And replace them with the new "disable hunter" flag ``HUNTER_ENABLED=OFF``: ethereum-mining/ethminer#219

**Comment by reagentoo** [comment]
Actually, it is not possible to remove all sed's with using `HUNTER_ENABLED=OFF` as long as developers practice this approach to development. And I think it will be safer to cut down the hunter using sed.

**Comment by 19504643** [comment]
Hi, I have been troubled by this problem building ethminer on windows with hunter,
but when I using the flag -DHUNTER_ENABLED=OFF, I get package required errors even I manually installed some libraries,
<<<<
CMake Error at CMakeLists.txt:64 (find_package):
  Could not find a package configuration file provided by "jsoncpp" with an
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.
>>>
but the boost library I installed worked without this error, how?
and how to use this sed script to disable hunter instead of using flag,thanks
